robot_radius: 0.4  
transform_tolerance: 50.0

map_type: voxel

# obstacle_layer:
#   enabled:              true
#   max_obstacle_height:  1.5 # 0.6
#   # min_obstacle_height:  0.2 # 0.6  # not documented, maybe does not exist
#   origin_z:             0.0
#   unknown_threshold:    10 # 1
#   mark_threshold:       0
#   combination_method:   0 #0: updateWithOverwrite 1: updateWithMax
#   track_unknown_space:  true    #true needed for disabling global path planning through unknown space
#   z_resolution: 0.2
#   z_voxels: 14
#   publish_voxel_map: true
#   observation_sources:  scan
#   footprint_clearing_enabled: true
#   scan:
#     expected_update_rate: 0 # if zero, the observation buffer returns isCurrent=true always
#     data_type: LaserScan
#     obstacle_range: 6.0  # 5.0
#     raytrace_range: 6.1  #5.0
#     topic: /scan
#     marking: true
#     clearing: true
#     min_obstacle_height: 0
#     max_obstacle_height: 1.5
#   laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

  # for debugging only, let's you see the entire voxel grid

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
# inflation_layer:
#   enabled:              true
#   cost_scaling_factor:  10.0 # exponential rate at which the obstacle cost drops off (default: 10)
#   inflation_radius:     0.4 # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
